# Generated by Django 3.2.5 on 2022-01-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_uuidvalue_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuidvalue',
            name='uuid',
            field=models.CharField(max_length=32),
        ),
    ]
